version: "3.9"

services:
  pypy39:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.pypy39
    volumes:
      - .:/usr/src/app

  pybind11:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.pybind11

  cython:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.cython

  cpython39:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.cpython39
    volumes:
      - .:/usr/src/app

  cpython311:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.cpython311
    volumes:
      - .:/usr/src/app

  nuitka:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.nuitka
